# Generated by Django 2.2.6 on 2019-11-08 14:20

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', django_extensions.db.fields.json.JSONField(blank=True, default={})),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, 'Wrong cost')])),
            ],
        ),
    ]
