# Generated by Django 2.2.6 on 2019-11-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(None, '-'), ('M', 'Male'), ('F', 'Female')], default='M', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbie',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Computer games', 'games')], default='Sport', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='user/images/user_default.jpg', null=True, upload_to='user/images/'),
        ),
    ]
